### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by anadon** [y-256/libdivsufsort#8] opened 2015-09-12 16:09 UTC
Following the build instructions in README.md results in a incomplete build, erroring because the define PROJECT_VERSION_FULL because of an omitted closing double quote.

**Comment by anadon** [comment] 2015-09-12 18:24
It looks like its due to a minor change in the git output formatting.

**Comment by kloetzl** [comment] 2015-09-13 09:10
This is a duplicate of issue #5 which can be fixed with the patch from PR #7.

**Comment by anadon** [comment] 2015-09-14 16:51
Is Mori Yuta not maintaining his code anymore?

**Comment by kloetzl** [comment] 2015-09-14 16:57
As far as I can tell, there was no activity since march.

**Comment by anadon** [comment] 2015-09-14 19:59
That move-over I thought was fully automated by google.  It seems odd to go through the effort of moving to a new host and then not care about what you moved.

**Comment by y-256** [comment] 2015-10-27 15:04
closed this in #7

**Closed by y-256** 2015-10-27 15:04 UTC
